#!/bin/sh



# Link the profile with all the magic variables
source ./.zprofile
unlink ~/.zprofile
ln -s $(realpath .zprofile) ~/.zprofile



# Link shell config
unlink ~/.zshrc
ln -s "$DOTS/.zshrc" ~



# Link everything important in the
# .config directory
# ------------------------------------------------

# tmux
unlink ~/.tmux.conf
ln -s "$DOTS/.config/tmux/tmux.conf" ~/.tmux.conf

# i3
rm -rf ~/.config/i3
ln -s "$DOTS/.config/i3" ~/.config

# polybar
rm -rf ~/.config/polybar
ln -s "$DOTS/.config/polybar" ~/.config

