#!/bin/sh



# Link the profile with all the magic variables
source ./.profile
unlink ~/.profile
ln -s $(realpath .profile) ~/.profile



# Link shell config
unlink ~/.zshrc
ln -s "$DOTS/.zshrc" ~



# Link everything important in the
# .config directory
# ------------------------------------------------

# tmux
unlink ~/.tmux.conf
ln -s "$DOTS/.config/tmux/tmux.conf" ~/.tmux.conf

# i3
rm -rf ~/.config/i3
ln -s "$DOTS/.config/i3" ~/.config

# bspwm
# sxhkd
rm -rf ~/.config/bspwm
rm -rf ~/.config/sxhkd
ln -s "$DOTS/.config/bspwm" ~/.config
ln -s "$DOTS/.config/sxhkd" ~/.config

# polybar
rm -rf ~/.config/polybar
ln -s "$DOTS/.config/polybar" ~/.config

