#!/bin/bash

# Installs sheldon so repos can be cloned easily


# Download rustup to install cargo
echo "[i] Downloading rustup"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh




# Source cargo so it's available
echo "[i] Sourcing .cargo so its available as a global command"
source $HOME/.cargo/env




# Install sheldon
echo "[i] Installing Sheldon"
cargo install sheldon