#!/usr/bin/env bash

rows=""
separator='\x0f'

rofi_theme="$(ix -f configs.rofi)/menus/notification-center"
rofi_args=(-dmenu -p "Notifications" -markup-rows -sep $separator -eh 3 -show-icons -theme $rofi_theme)

log_file=$(ix -f logs.dunst)
json=$(cat "$log_file")

notifications=$( 
  echo $json | \
    jq -cr '.notifications[] | "\(.appname)|\(.summary)|\(.icon)|\(.urgency)|\(.timestamp)|\(.body)"'
)



while IFS="|" read -r appname summary icon urgency timestamp body; do
  name="$(printf %-62.62s "<b>$appname: </b>$summary")"
  icon="\0icon\x1f${icon}"

  entry="$name$timestamp\n$body$icon$separator"

  rows="$rows$entry"
done <<< $notifications

echo -en "$rows" | rofi "${rofi_args[@]}"

