#!/usr/bin/env bash

rows=""
separator='\x0f'

rofi_theme="$(ix -f configs.rofi)/menus/notification-center"
rofi_args=(-dmenu -i -p "Notifications" -markup-rows -sep $separator -eh 3 -show-icons -theme $rofi_theme)

log_file=$(ix -f logs.dunst)
json=$(cat "$log_file")

# Parse the notifications array
notifications=$( 
  echo $json | \
    jq -cr '.notifications[] | "\(.appname)|\(.summary)|\(.icon)|\(.urgency)|\(.timestamp)|\(.body)"'
)


row_count=0
urgent_items=""
active_items=""

while IFS="|" read -r appname summary icon urgency timestamp body; do
  # Add the notification to the active elements list
  if [[ "$urgency" == *"NORMAL"* ]]; then
    active_items=${active_items}${active_items:+,}$row_count
  fi

  # Add the notification to the urgent element list
  if [[ "$urgency" == *"CRITICAL"* ]]; then
    urgent_items=${urgent_items}${urgent_items:+,}$row_count
  fi


  name="$(printf %-76.76s "<b>$appname: </b>$summary")"
  icon="\0icon\x1f${icon}"

  entry="$name$timestamp\n$body$icon$separator"

  rows="$rows$entry"
  row_count=$(( row_count + 1 ))
done <<< $notifications



echo -en "$rows" | rofi "${rofi_args[@]}" -a "$active_items" -u "$urgent_items"

