#!/usr/bin/env bash

rows=""
separator='\x0f'

rofi_theme="$(ix -f configs.rofi)/menus/notification-center"
rofi_args=(-dmenu -p "Notifications" -markup-rows -sep $separator -eh 3 -show-icons -theme $rofi_theme)

log_file=$(ix -f logs.dunst)
json=$(cat "$log_file")

notifications=$( 
  echo $json | \
  jq -cr '.notifications[] | "\(.appname)|\(.summary)|\(.icon)|\(.urgency)|\(.timestamp)"'
)



while IFS="|" read -r appname summary icon urgency timestamp; do
  name="<b>$(printf %-62.62s "$appname")</b>"
  icon="\0icon\x1f${icon}"

  entry="$name$timestamp\n$summary$icon$separator"

  rows="$rows$entry"
done <<< $notifications

echo -en "$rows" | rofi "${rofi_args[@]}"

