#!/usr/bin/env ruby
$: << ENV['katana']


require 'ui/menu'
require 'etc/logs'
require 'json'



logger = Logs::get('dunst')
notifications = logger.all()


menu = Menu::new(:custom)
  .line_separator("\x0F")
  .theme('notification-center')
  .prompt("(#{notifications.length()})")
  .max_lines(5)
  .markup()
  .insensitive()
  .icons()

# If the log doesn't exist show an empty menu
if not notifications
  menu.add_line('No notifications (^-^*)')
  menu.show()
  exit
end



notifications.each do |log|
  # Awful formatting but it looks nice in the end I guess...
  ident = "<big>#{log['appname']}</big>".ljust(45, ' ')
  icon  = "\0icon\x1f#{log['icon']}"
  summary = log['summary']
  
  urgency   = log['urgency']
  timestamp = "<span alpha='50%'>#{log['timestamp']}</span>"
  body      = "<small>#{log['body']}</small>"

  full_line = "#{ident}#{timestamp}\n\n#{summary}\n#{body}#{icon}"
  line_status = nil

  # Set lines as active or urgent depending
  # on the specified urgency. We only care
  # about NORMAL and CRITICAL.
  case urgency
  when 'NORMAL';    line_status = :active
  when 'CRITICAL';  line_status = :urgent
  end

  if line_status
    menu.add_line(full_line, line_status)
  else
    menu.add_line(full_line)
  end
end



menu.show()


