#!/usr/bin/env bash

#: ix-config
#: prefix: $
#: to: ${{ configs.menus }}
#: access: 777

ROFI_OPTIONS=(-theme ${{ configs.rofi }}/menus/power-menu)
ROFI_CONFIRMATION=(-theme ${{ configs.rofi }}/menus/confirmation-dialog)
CONFIRMATION_OPTIONS=(-dmenu -i -p "Are you sure you want to proceed?")


power_off="󰐥"
reboot="󰜉"
lock="󱅞"
suspend="󰒲"
log_out="󰗽"

options="$power_off\n$reboot\n$lock\n$suspend\n$log_out"
chosen="$(echo -e "$options" | rofi "${ROFI_OPTIONS[@]}" -dmenu -selected-row 2)"

YESNO="\n"

case $chosen in
    $power_off)
        [ $(echo -e $YESNO | rofi "${ROFI_CONFIRMATION[@]}" "${CONFIRMATION_OPTIONS[@]}") ==  ] && systemctl poweroff
        ;;
    $reboot)
        [ $(echo -e $YESNO | rofi "${ROFI_CONFIRMATION[@]}" "${CONFIRMATION_OPTIONS[@]}") ==  ] && systemctl reboot
        ;;
    $lock)
        exec  $( ix -f paths.scripts )/lock/lock-screen
        ;;
    $suspend)
	    [ $(echo -e $YESNO | rofi "${ROFI_CONFIRMATION[@]}" "${CONFIRMATION_OPTIONS[@]}") ==  ] && slock
        ;;
    $log_out)
	    [ $(echo -e $YESNO | rofi "${ROFI_CONFIRMATION[@]}" "${CONFIRMATION_OPTIONS[@]}") ==  ] && bspc quit
        ;;
esac
