#!/bin/sh




FONT="FiraCode Nerd Font"



i3lock-color -n -c 24283100 -t -e 		\
	--datestr="" 				\
	--blur=5 				\
	--indicator				\
	--force-clock				\
	--pass-media-keys			\
	--pass-power-keys			\
	--pass-volume-keys			\
	--insidevercolor=2e3440a8		\
	--insidewrongcolor=2e3440a8		\
	--insidecolor=2e344000			\
	--ringwrongcolor=bf616a			\
	--ringcolor=81a1c1			\
	--ringvercolor=88c0d0			\
	--line-uses-inside			\
	--keyhlcolor=b48ead			\
	--bshlcolor=bf616a			\
	--separatorcolor=81a1c1			\
	--verifcolor=88c0d0			\
	--wrongcolor=bf616a			\
	--indpos="w/2:h/2-30"			\
	--timecolor=e5e9f0			\
	--timepos="w/2:h/2+55"			\
	--timestr="%I:%M %p"			\
	--datecolor=e5e9f0			\
	--time-font="$FONT"			\
	--date-font="$FONT"			\
	--verif-font="$FONT"			\
	--wrong-font="$FONT"			\
	--greeter-font="$FONT:style=Bold"	\
	--greetertext="$USER"			\
	--greetercolor=8fbcbb			\
	--greeterpos="w/2:h/2+40"		\
	--radius 50				\
	--ring-width 3				\
	--greetersize=14			\
	--timesize=12				\
	--verifsize=10				\
	--wrongsize=10				\
	--modsize=9				\
	--modifpos="w/2:h/2-15"


