#!/usr/bin/env ruby
$: << ENV['katana']


require 'audio'

# Setup the audio module
Audio::setup()


muted = Audio::is_muted()
headphones = Audio::using_headphones()


if muted
  if headphones
    print '󰟎'
    exit
  end

  print '󰖁'
  exit
end


# If just headphones and not muted
if headphones
  print '󰋋'
  exit
end



# If no headphones, figure out the appropriate
# icon for the volume level
volume = Audio::current_volume()

case volume
when 60..100
  print '󰕾'

when 30..60
  print '󰖀'

when 0..30
  print '󰕿'

end
