#!/usr/bin/env ruby
$: << ENV['katana']

require 'utils'

use 'system'


# Official updates/AUR updates
updates = System::updates()
total_updates = updates[:pac] + updates[:aur]

# No output if there are no updates
if total_updates == 0
  exit(1)
end

final = []
# Get the configured colors
blue = `ix -f colors.blue`.strip
green = `ix -f colors.light-green`.strip

# Different colors for each update tpye
# They have to be formatted here since we can't play
# with script output inside the polybar config
if updates[:pac] > 0
  final.push("%{F#{green}}#{updates[:pac]} 󰏗%{F-}")
end

if updates[:aur] > 0
  final.push("%{F#{blue}}#{updates[:aur]} 󰏖%{F-}")
end


# Output the label that polybar should show
puts final.join(' ')

