#!/usr/bin/env ruby
$: << ENV['katana']


require 'dev/backlight'
require 'etc/notify'


case ARGV[0]
when 'down'
  Backlight::lower()

when 'up'
  Backlight::raise()

end


brightness = Backlight::screen_level().to_f.round

Notification::new(62423)
  .appname('brightness')
  .summary("#{brightness}%")
  .hint("int:value:#{brightness}")
  .replace
  .send
