#!/usr/bin/env ruby
$: << ENV['katana']


require 'dev/audio'
require 'etc/notify'



case ARGV[0]
when 'up'
  Microphone::raise()

when 'down'
  Microphone::lower()

when 'toggle'
  Microphone::toggle()

end



notification = Notification::new(642513)
  .appname('microphone')
  .summary('muted')
  .replace


if not Microphone::is_muted()
  volume = Microphone::current_volume()

  notification
    .summary("#{volume}%")
    .hint("int:value:#{volume}")
end


notification.send()
