#!/usr/bin/env ruby
$: << ENV['katana']


require 'audio'
require 'notify'


# Setup audio module
Audio::setup()


# Execute based on provided arguments
case ARGV[0]
when 'up'
  Audio::raise(5)

when 'down'
  Audio::lower(5)

when 'toggle'
  Audio::toggle()

end


# Build a notification
# and give it an ID so it can be replaced if needed
notification = Notification::new(51341)
  .summary("muted")
  .appname('volume')
  .urgency(:low)
  .replace()


if not Audio::is_muted()
  volume = Audio::current_volume()

  notification
    .summary("#{volume}%")
    .hint("int:value:#{volume}")
end


notification.send()


