#!/usr/bin/env bash
# changeVolume


# Arbitrary but unique message id
msgId="991049"

# Change the volume
case "$1" in
    "up")
        amixer set Master 5%+
        ;;

    "down")
        amixer set Master 5%-
        ;;

    "toggle")
        # Do both since headphones is dependent on master
        amixer set Master toggle
        amixer set Headphone toggle
        ;;
esac

# Query amixer for the current volume and whether or not the speaker is muted
# Tailed line looks like this:
#   For speakers: "Mono: Playback 36 [100%] [0.000dB] [on]"
#   For headphones: "Front right: Playback 87 [100%] [0.000dB] [on]"
last=$(amixer get Master | tail -1 | awk -F':' '{print $2}')

volume="$( echo $last | awk '{print $3}' | sed 's/[^0-9]*//g')"
mute="$(echo $last | awk '{print $5}' | sed 's/[^a-z]*//g')"

if [[ $volume == 0 || "$mute" == "off" ]]; then
    # Show the sound muted notification
    dunstify -a "changeVolume" -u low -i audio-volume-muted -r "$msgId" "Volume muted" 
else
    # Show the volume notification
    dunstify -a "changeVolume" -u low -i audio-volume-high -r "$msgId" -h int:value:"$volume" "Volume: ${volume}%"
fi
