#!/usr/bin/env bash

# Follow in the steps of mighty barbarossa
# Cleanup to ensure each field is on a separate line
appname=$(echo "$1" | sed '/^$/d')
summary=$(echo "$2" | sed '/^$/d' | xargs)
body=$(echo "$3" | sed '/^$/d' | xargs)
icon=$(echo "$4" | sed '/^$/d')
urgency=$(echo "$5" | sed '/^$/d')
timestamp=$(date +"%I:%M %p") # For now


# Check if app is blacklisted
case "$appname" in
	'changeVolume'|'changeBrightness'|'sxhkd'|'bspwm')
		# Don't add notification
		exit
		;;
esac



# Check if the logfile is there
# TODO: Replace with ix variable
if [ ! -f /tmp/dunstlog ]; then
	echo "FILE DOESNT EXIST"
	echo '{ "notifications": [] }' > /tmp/dunstlog
fi



# Build a new JSON object for the notification
json=$(
	jq -n \
		--arg an "$appname" \
		--arg sy "$summary" \
		--arg by "$body" \
		--arg ic "$icon" \
		--arg uy "$urgency" \
		--arg ts "$timestamp" \
		'{appname:$an, summary:$sy, body:$by, icon:$ic, urgency:$uy, timestamp:$ts}'
)


# Temporary file to write the new contents to
swap="/tmp/${RANDOM}.tmp"

# Prepend the new JSON object to the existing array
jq ".notifications |= [$json] + ." /tmp/dunstlog > $swap
mv $swap /tmp/dunstlog

