#!/bin/bash


# Download & install plugins
echo "[i] Downloading zsh plugins"
sheldon source




# Symlink downloaded '.oh-my-zsh' to '~/.oh-my-zsh'
echo "[i] Linking oh-my-zsh"
ln -sfn $PWD/repositories/github.com/robbyrussell/oh-my-zsh ~/.oh-my-zsh




# Symlink '.zshrc' to '~/.zshrc'
echo "[i] Linking .zshrc"
ln -sfn $PWD/.zshrc ~/.zshrc
