add_newline = true

format = "$python$git_status$git_branch$directory[](white) "


[git_branch]
format = "[$branch]($style) "
style = "bold grey"
truncation_length = 10
truncation_symbol = "..."


[git_status]
style = "black"


[python]
format = "($virtualenv) "
