add_newline = true

format = "$git_status$git_branch$directory$env_var[](white) "


[git_branch]
format = "[$branch]($style) "
style = "bold grey"
truncation_length = 10
truncation_symbol = "..."


[git_status]
style = "black"


[env_var]
variable = "CURRENT_ENVIRONMENT"
format = "[$env_value ]($style)"
style = "bold green"

